### ISSUE TITLE
Папки v0.1, v0.2, ...

### ISSUE THREAD

**Issue by Semigradsky** [ITMaks/Shop#1]
Для ссылок на разные версии продукта как правило используют теги.
Для того, чтобы дать возможность удобно пользователям скачать нужную версию используют релизы - https://help.github.com/articles/creating-releases/

Пример всего этого счастья можно посмотреть, [например, здесь](https://github.com/twbs/bootstrap/releases).

**Comment by ITMaks** [comment]
Большое спасибо!
